// Objetos/productos del e-commers

const tienda = [{
    id:1,
    nombre: 'Remera Titular de San Lorenzo de Almagro',
    precio: 26999,
    categoria:'Remeras',
    foto: '../img/rem-1.jpg',
    cantidad: 1,
},

{
    id:2 ,
    nombre:'Remera Suplente de San Lorenzo de Almagro' ,
    precio: 26999,
    categoria:'Remeras',
    foto:'../img/rem-2.webp',
    cantidad: 1,
},
{
    id:3 ,
    nombre:'Segunda Remera Suplente de San Lorenzo de Almagro',
    precio: 26999,
    categoria:'Remeras',
    foto:'../img/rem-dor.png',
    cantidad: 1,  
},
{
    id:17,
    nombre: 'Remera del Arquero Titular de San Lorenzo de Almagro',
    precio: 23999,
    categoria:'Remeras',
    foto: '../img/rem-arq1.jpg',
    cantidad: 1, 
},
{
    id:4 ,
    nombre:'Buzo Frizado Blanco de San Lorenzo de Almagro' ,
    precio:16800 ,
    categoria:'Buzos de San Lorenzo de Almagro' ,
    foto:'../img/buzo-wit.png',
    cantidad: 1,
},
{
    id:5 ,
    nombre:'Campera Combinada Con Capucha San Lorenzo de Almagro' ,
    precio: 20900 ,
    categoria:'Buzos de San Lorenzo de Almagro' ,
    foto:'../img/buzo-capred.webp',
    cantidad: 1,
},
{
    id:6 ,
    nombre:'Buzo Combinado San Lorenzo' ,
    precio: 9520,
    categoria: 'Buzos de San Lorenzo de Almagro',
    foto:'../img/buzo-sim.webp',
    cantidad: 1,
},
{
    id:7 ,
    nombre:'Chomba Combinada Azul de San Lorenzo de Almagro' ,
    precio: 7900,
    categoria:'Remeras',
    foto:'../img/rem-cot.webp',
    cantidad: 1,
},
{
    id:8 ,
    nombre:'Chomba Combinada Gris de San Lorenzo de Almagro' ,
    precio:7900 ,
    categoria:'Remeras' ,
    foto:'../img/rem-cot2.webp',
    cantidad: 1,
},
{
    id:9 ,
    nombre:'Buzo Frizado Estampado Azul de San Lorenzo de Almagro' ,
    precio:19500 ,
    categoria:'Buzos de San Lorenzo de Almagro' ,
    foto:'../img/buzo-capblue.png',
    cantidad: 1,
},
{
    id:10 ,
    nombre:'Buzo Frizado Rojo de San Lorenzo de Almagro' ,
    precio:16800,
    categoria:'Buzos de San Lorenzo de Almagro' ,
    foto:'../img/buzo-red.webp',
    cantidad: 1,
},
{
    id:11 ,
    nombre:'Remera Casual con Diseño Azul de San Lorenzo de Almagro' ,
    precio:7900 ,
    categoria:'Remeras' ,
    foto:'../img/rem-blue.webp',
    cantidad: 1,
},
{
    id:12 ,
    nombre:'Remera Casual Simple Negra de San Lorenzo de Alamgro ' ,
    precio:5600 ,
    categoria:'Remeras' ,
    foto:'../img/rem-neg.webp',
    cantidad: 1,
},
{
    id:13 ,
    nombre:'Conjunto de Algodon Friza de San Lorenzo de Almagro' ,
    precio:16000 ,
    categoria:'Conjunto' ,
    foto:'../img/conj-alg.webp',
    cantidad: 1,
},
{
    id:14 ,
    nombre:'Pelota Dribbling San Lorenzo Mundial 2.0' ,
    precio:6200 ,
    categoria:'Pelotas' ,
    foto:'../img/pelota-2.jpg',
    cantidad: 1,
},
{
    id:15 ,
    nombre:'Pelota Dribbling San Lorenzo' ,
    precio:6200 ,
    categoria:'Pelotas' ,
    foto:'../img/pelota-1.jpg',
    cantidad: 1,
},
{
    id:16 ,
    nombre:'Conjunto de Entrenamiento Campera Y Pantalon de San Lorenzo de Almagro' ,
    precio:14500 ,
    categoria:'Conjunto' ,
    foto:'../img/conj-entr.jpg',
    cantidad: 1,
},
{
    id:16 ,
    nombre:'Conjunto de Entrenamiento Campera Y Pantalon de San Lorenzo de Almagro' ,
    precio:14500 ,
    categoria:'Conjunto' ,
    foto:'../img/conj-dep.jpg',
    cantidad: 1,
},
]
